@echo off
echo Iniciando servidor de desarrollo en segundo plano...
start /B npm run dev
echo Esperando a que el servidor inicie...
timeout /t 5 /nobreak >nul
echo Abriendo navegador en http://localhost:4900...
start http://localhost:4900
echo Servidor iniciado. Presiona cualquier tecla para cerrar esta ventana...
pause >nul
